version: "3"
services:
  chirpstack-fuota-server:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-fuota-server
    links:
      - postgres
    environment:
      - TEST_POSTGRES_DSN=postgres://chirpstack_fuota:chirpstack_fuota@postgres/chirpstack_fuota?sslmode=disable
    ports:
      - 8090:8090
      - 8080:8080
      - 8070:8070
      
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d
